services:
  # Creates the database service.
  db:
    # The image being used. Currently the "lastest" postgres image.
    image: postgres
    # Restart on error unless manually stopped.
    restart: unless-stopped
    environment:
      # Sets the password for the database user.
      POSTGRES_PASSWORD: secret
    #Exposes port 5432 to the host.
    ports:
      - 5432:5432
    # Use the backend container network.
    networks:
      - backend
    # Create persistent data by saving to a docker volume.
    volumes:
      - ghg-data:/var/lib/postgresql/data
  # For building the api service image
  build-api:
    # names the service.
    image: spring-api
    # Where the source code and Dockerfile live.
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    # Set this so spring can find the db as it differs from on localhost.
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    networks:
      - backend
  client-nginx:
    image: client-nginx
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 8081:80
  client-vite:
    image: client-vite
    build:
      context: ./frontend/
      dockerfile: Dockerfile-vite
    volumes:
      - type: bind
        source: ./frontend/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./frontend/vite.config.js
        target: /usr/src/app/vite.config.js
    networks:
      - backend
    ports:
      - 5173:5173
# Creates the volume.
volumes:
  ghg-data:
# Creates the network. Can later create a frontend network to seperate
# the frontend and backend.
networks:
  backend:
  frontend:
